# Generated by Django 3.2 on 2021-04-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0003_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to=''),
        ),
    ]
