# Generated by Django 3.2 on 2021-04-27 10:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0006_remove_product_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+911111111111', max_length=128, region=None),
        ),
    ]
