# Generated by Django 3.2 on 2021-05-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0009_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Brand', max_length=255),
        ),
    ]
